# ---------------------------------------------------------------------
title: RG Hamburg
description: Radsport-Gemeinschaft Hamburg von 1893 e.V.
instagram_url: "https://instagram.com/rg_hamburg"

address:
  name: Radsport-Gemeinschaft Hamburg von 1893 e.V.
  street: Stormsweg 3
  city: 22085 Hamburg

nav:
  - id: aktuelles
    label: Aktuelles
    href: "/aktuelles/"
  - id: disziplinen
    label: Disziplinen
    dropdown: true
  - id: verein
    label: Verein
    href: "/#verein"
  - id: partner
    label: Partner
    href: "/#partner"

footer_links:
  - label: Zeitmessung
    href: "#"
  - label: EasyVerein
    href: "#"
  - label: Kontakt
    href: "/probetraining/"
  - label: Impressum
    href: "/impressum.html"
  - label: Datenschutz
    href: "/datenschutzerklaerung.html"
  - label: Mitgliedschaft
    href: "/mitgliedschaft.html"

# ---------------------------------------------------------------------
hero:
  heading: "Ready to Race"
  subheading: "Egal, ob entspannte Gruppenfahrten, rasante Straßenrennen oder BMX Rides. Wir machen dich startklar!"
  cta_label: "Erfahre mehr"
  cta_href: "#disziplinen"
  slides:
    - image: hero-road.png
      alt: Radsport Hamburg
      label: Rennsport
    - image: hero-bmx.png
      alt: BMX
      label: BMX
    - image: hero-gravel.png
      alt: "Gravel & MTB"
      label: "Gravel & MTB"

# ---------------------------------------------------------------------
disciplines:
  - name: Rennsport
    url: /rennsport/
    image: discipline-rennsport.png
    description: "Auf dich wartet ein junges Team aus den besten Radsportlern Hamburgs unter der Anleitung von erfahrenen Trainern."
    btn_label: Erfahre mehr
  - name: BMX
    url: /bmx/
    image: discipline-bmx.png
    description: "Auf dich wartet ein junges Team aus den besten Radsportlern Hamburgs unter der Anleitung von erfahrenen Trainern."
    btn_label: Erfahre mehr
  - name: "Gravel & MTB"
    url: /gravel/
    image: discipline-gravel.png
    description: "Auf dich wartet ein junges Team aus den besten Radsportlern Hamburgs unter der Anleitung von erfahrenen Trainern."
    btn_label: Erfahre mehr

# ---------------------------------------------------------------------
partners:
  - name: Sparkasse Holstein
    image: sponsor-sparkasse.png
  - name: Active City Hamburg
    image: sponsor-activecity.png
  - name: MGF Gartenstadt Farmsen
    image: sponsor-mgf.png
  - name: Velux
    image: sponsor-velux.png
