title: RG Hamburg
description: Radsport-Gemeinschaft Hamburg von 1893 e.V.
instagram_url: "https://instagram.com"

address:
  name: Radsport-Gemeinschaft Hamburg von 1893 e.V.
  street: Stormsweg 3
  city: 22085 Hamburg

nav:
  - id: aktuelles
    label: Aktuelles
    href: "/#aktuelles"
  - id: disziplinen
    label: Disziplinen
    href: "/disziplinen/bmx/"
  - id: verein
    label: Verein
    href: "/#verein"
  - id: partner
    label: Partner
    href: "/#partner"

footer_links:
  - label: Zeitmessung
    href: "#"
  - label: EasyVerein
    href: "#"
  - label: Kontakt
    href: "#"
  - label: Impressum
    href: "/impressum/"
  - label: Datenschutz
    href: "/datenschutzerklaerung/"
  - label: Mitgliedschaft
    href: "/mitgliedschaft/"
