# ---------------------------------------------------------------------
title: RG Hamburg
description: Radsport-Gemeinschaft Hamburg von 1893 e.V.
instagram_url: "https://instagram.com/rg_hamburg"

address:
  name: Radsport-Gemeinschaft Hamburg von 1893 e.V.
  street: Stormsweg 3
  city: 22085 Hamburg

nav:
  - id: aktuelles
    label: Aktuelles
    href: "/aktuelles/"
  - id: disziplinen
    label: Disziplinen
    dropdown: true
  - id: verein
    label: Verein
    href: "/verein/"
  - id: partner
    label: Partner
    href: "/#partner"

footer_links:
  - label: Zeitmessung
    href: "#"
  - label: EasyVerein
    href: "#"
  - label: Kontakt
    href: "/probetraining/"
  - label: Impressum
    href: "/impressum.html"
  - label: Datenschutz
    href: "/datenschutzerklaerung.html"


# ---------------------------------------------------------------------
hero:
  heading: "Ready to Race"
  subheading: "Egal, ob entspannte Gruppenfahrten, rasante Straßenrennen oder BMX Rides. Wir machen dich startklar!"
  cta_label: "Erfahre mehr"
  cta_href: "#disziplinen"
  slides:
    - image: hero-road.png
      alt: Radsport Hamburg
      label: Rennsport
    - image: hero-bmx.png
      alt: BMX
      label: BMX
    - image: hero-gravel.png
      alt: "Gravel & MTB"
      label: "Gravel & MTB"

# ---------------------------------------------------------------------
disciplines:
  - name: Rennsport
    url: /rennsport/
    image: discipline-rennsport.png
    description: "Vom Lizenzrennen bis zur RTF-Ausfahrt: Rennsport bei der RG Hamburg vereint Wettkampf und Gemeinschaft. Heimrennen: der Große Preis von Volksdorf, seit 1983."
    btn_label: Erfahre mehr
  - name: BMX
    url: /bmx/
    image: discipline-bmx.png
    description: "Acht Fahrer, ein Startblock, 300 Meter Vollgas — mit Sprüngen, Kurven und echtem Herzrasen. BMX Racing ist familientauglich, olympisch und bei uns in Hamburg zuhause."
    btn_label: Erfahre mehr
  - name: "Gravel & MTB"
    url: /gravel/
    image: discipline-gravel.png
    description: "Schotter, Feldwege und Hamburger Umland: Unsere Gravel Rides erkunden sonntags die Region — getrennte Gruppen für Einsteiger und Erfahrene, immer gemeinsam unterwegs."
    btn_label: Erfahre mehr

# ---------------------------------------------------------------------
verein:
  vorstand:
    - name: Homer Simpson
      role: 1. Vorsitzender
      email: homer@rg-hamburg.de
    - name: Marge Simpson
      role: 2. Vorsitzende
      email: marge@rg-hamburg.de

  spartenleitung:
    - name: Lisa Simpson
      role: Spartenleiterin Rennsport
      email: lisa@rg-hamburg.de
    - name: Bart Simpson
      role: Spartenleiter BMX
      email: bart@rg-hamburg.de
    - name: Ned Flanders
      role: Spartenleiter Gravel & MTB
      email: ned@rg-hamburg.de

# ---------------------------------------------------------------------
partners:
  - name: Sparkasse Holstein
    image: sponsor-sparkasse.png
  - name: Active City Hamburg
    image: sponsor-activecity.png
  - name: MGF Gartenstadt Farmsen
    image: sponsor-mgf.png
  - name: Velux
    image: sponsor-velux.png

# ---------------------------------------------------------------------
kontakt:
  image: kontakt.png
  heading: "Noch Fragen? Du möchtest Mitglied werden?"
  text: 'Kein Problem: Nehme Kontakt zu uns auf und wir werden uns umgehend melden.'
  cta_label: Kontaktformular
  cta_href: "#"

# ---------------------------------------------------------------------
tags:
  bmx:
    label: BMX
    default_image: news/Rennen_1.jpeg
  rennsport:
    label: Rennsport
    default_image: news/Rennen1.jpeg
  gravel:
    label: Gravel & MTB
    default_image: news/Rennen1.jpeg
  verein:
    label: Verein
    default_image: news/vereinsfeier-2026-jubilare-ehrung.jpg

# ---------------------------------------------------------------------
instagram:
  rg_hamburg:
    posts:
      - image: social-1.png
        alt: Instagram Post
      - image: social-2.png
        alt: Instagram Post
      - image: social-3.png
        alt: Instagram Post
  bmx_rghamburg:
    posts:
      - image: social-4.jpg
        url: "https://www.instagram.com/p/DUNlw2CDUQv/"
        alt: Instagram Post
      - image: social-5.jpg
        url: "https://www.instagram.com/p/DQ5BFU0jeUz/"
        alt: Instagram Post
      - image: social-6.jpg
        url: "https://www.instagram.com/p/DPwjNRzCLrs/"
        alt: Instagram Post
